name: 'books_data_transformations' # تأكد أن هذا يطابق اسم مشروعك الجديد إذا غيرته
version: '1.0.0'
config-version: 2

profile: 'books_data_transformations' # تأكد أن هذا يطابق اسم ملف تعريف الاتصال الخاص بك

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  books_data_transformations:
    +materialized: view # الافتراضي هو view لكل النماذج
    staging:
      +materialized: view # اجعل نماذج Staging عروض (views)
    marts:
      +materialized: table # اجعل نماذج Marts جداول (tables)