version: 2

sources:
  - name: books_db_source
    database: books # تأكد أن هذا يطابق تماماً اسم قاعدة البيانات في Snowflake
    schema: PUBLIC # تأكد أن هذا يطابق تماماً اسم المخطط في Snowflake
    tables:
      - name: BOOKS_RAW # تأكد أن هذا يطابق تماماً اسم الجدول في Snowflake
        description: "Raw book data scraped from books.toscrape.com"