my_new_dbt_project:
  outputs:
    dev:
      account: AZUWYTO-WQ25007
      database: books
      password: Kokokokokoko#400
      role: ACCOUNTADMIN
      schema: PUBLIC
      threads: 1
      type: snowflake
      user: ABOBAKAR
      warehouse: book_store
  target: dev